---
- name: Git checkout with key
  delegate_to: '{{ ansible_controller }}'
  ansible.builtin.git:
    repo: '{{ git_repo_url }}'
    dest: '{{ playbook_dir }}/bin/{{ git_repo_name }}'
    key_file: '{{ git_key_file }}'
    version: development
    accept_hostkey: true
    force: true
  when: git_key_file is defined
  register: result

- name: Git checkout without key (unauthenticated)
  delegate_to: '{{ ansible_controller }}'
  ansible.builtin.git:
    repo: '{{ git_repo_url }}'
    dest: '{{ playbook_dir }}/bin/{{ git_repo_name }}'
    accept_hostkey: true
    force: true
  when: git_key_file is not defined
  register: result

- name: Copy to remote
  become: true
  ansible.builtin.copy:
    src: '{{ playbook_dir }}/bin/{{ git_repo_name }}'
    dest: '{{ git_repo_destination }}'
    owner: '{{ git_repo_destination_owner }}'
    group: '{{ git_repo_destination_group }}'
    mode: '0640'
  when: git_repo_subfolder is not defined and git_repo_stay_local is not defined

- name: Copy to remote as subfolder
  become: true
  ansible.builtin.copy:
    src: '{{ playbook_dir }}/bin/{{ git_repo_name }}/{{ git_repo_subfolder }}'
    dest: '{{ git_repo_destination }}'
    owner: '{{ git_repo_destination_owner }}'
    group: '{{ git_repo_destination_group }}'
    mode: '0640'
  when: git_repo_subfolder is defined and git_repo_stay_local is not defined
