---
- name: Add Telegraf's official GPG key
  become: true
  ansible.builtin.apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present

- name: Add Telegraf repository
  become: true
  ansible.builtin.apt_repository:
    repo: 'deb https://repos.influxdata.com/{{ OS_ID }} {{ OS_VERSION_CODENAME }} stable'
    state: present

- name: Install Telegraf
  become: true
  ansible.builtin.apt:
    name: '{{ item }}'
    state: latest
    update_cache: true
  loop:
    - telegraf

- name: Modify default configuration to do very little
  become: true
  ansible.builtin.shell: |
    telegraf --output-filter false --input-filter false config > /etc/telegraf/telegraf.conf
  tags:
    - never

- name: Create config
  become: true
  ansible.builtin.shell: |
    telegraf config > telegraf.conf

# TODO Add wanted inputs and outputs

- name: Start Telegraf service and set it to start on boot
  become: true
  ansible.builtin.service:
    name: telegraf
    state: restarted
    enabled: true
