# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.box = 'fedora/41-cloud-base'
  config.vm.box_version = '41-20241024.0'

  config.vm.provider 'qemu' do |q|
    q.memory = '2048'
    q.cpus = '2'
  end

  config.vm.provision 'shell', inline: <<-SHELL
    echo "--- Setting up ansible user ---"
    # Create the 'ansible' user
    useradd ansible

    # Create the .ssh directory
    mkdir -p /home/ansible/.ssh
    chmod 700 /home/ansible/.ssh

    # Copy your public SSH key from the project directory to the VM.
    # The /vagrant directory inside the VM is a synced folder to your project directory.
    cp /vagrant/vagrant_sshkey.pub /home/ansible/.ssh/authorized_keys

    # Set correct permissions for the authorized_keys file
    chmod 600 /home/ansible/.ssh/authorized_keys

    # Set correct ownership for the user's home directory
    chown -R ansible:ansible /home/ansible

    echo "--- Granting passwordless sudo to ansible user ---"
    # Create a sudoers file to grant passwordless sudo permissions
    echo "ansible ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/ansible
  SHELL
end
