---
- name: Stop systemd unit
  become: true
  ansible.builtin.systemd:
    state: stopped
    name: duckdns_updater.timer
    enabled: true
  ignore_errors: true

- name: Create systemd service unit
  become: true
  ansible.builtin.copy:
    dest: /etc/systemd/system/duckdns_updater.service
    content: |
      [Unit]
      Description=Updates duckdns.org domains
      After=multi-user.target
      [Service]
      Type=oneshot
      Restart=no
      ExecStart=curl https://www.duckdns.org/update?domains={{ duckdns.domains }}&token={{ duckdns.token }}
      [Install]
      WantedBy=multi-user.target

- name: Create systemd timer unit
  become: true
  ansible.builtin.copy:
    dest: /etc/systemd/system/duckdns_updater.timer
    content: |
      [Unit]
      Description=Start Duckdns Updater service
      [Timer]
      OnCalendar=*:0/3
      [Install]
      WantedBy=timers.target

- name: Start systemd unit timer
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    state: restarted
    name: duckdns_updater.timer
    enabled: true
