---
- name: Set facts
  ansible.builtin.set_fact:
    user_name: influxdb
    group_name: influxdb
    home_dir: '/home/influxdb'
    repo_folder: 'influxdb'

- name: Ensure user with correct settings exists
  ansible.builtin.include_role:
    name: docker_enabled_user_creator
  vars:
    name: '{{ user_name }}'
    user_group: '{{ group_name }}'
    home: '{{ home_dir }}'

- name: Install Influxdb
  ansible.builtin.include_role:
    name: git_installer
  vars:
    git_repo_url: '{{ git_repositories.influxdb }}'
    git_repo_name: '{{ repo_folder }}'
    git_repo_destination: '{{ home_dir }}'
    git_repo_destination_owner: '{{ user_name }}'
    git_repo_destination_group: '{{ group_name }}'

- name: Create .env
  no_log: yes
  become: yes
  ansible.builtin.copy:
    dest: '{{ home_dir }}/{{ repo_folder }}/.env'
    owner: '{{ user_name }}'
    group: '{{ group_name }}'
    mode: '0640'
    content: |
      DOCKER_NETWORK={{ docker.network }}
      DOCKER_INFLUXDB_INIT_USERNAME: {{ influxdb.username }}
      DOCKER_INFLUXDB_INIT_PASSWORD: {{ influxdb.password }}
      DOCKER_INFLUXDB_INIT_ORG: {{ influxdb.org }}
      DOCKER_INFLUXDB_INIT_BUCKET: {{ influxdb.bucket }}

- name: Stop Influxdb
  become: true
  become_user: '{{ user_name }}'
  community.docker.docker_compose_v2:
    project_src: '{{ home_dir }}/{{ repo_folder }}'
    state: absent

- name: Start Influxdb
  become: true
  become_user: '{{ user_name }}'
  community.docker.docker_compose_v2:
    build: always
    project_src: '{{ home_dir }}/{{ repo_folder }}'
    state: present
