---
- name: Ensure group "docker" exists
  become: true
  ansible.builtin.group:
    name: docker
    state: present

- name: Install Docker dependencies
  become: true
  ansible.builtin.apt:
    name: '{{ item }}'
    state: present
    update_cache: true
  loop:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release

- name: Add Docker's official GPG key
  become: true
  ansible.builtin.shell: |
    sudo mkdir -p /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    sudo chmod a+r /etc/apt/keyrings/docker.gpg

- name: Set up Docker repository
  become: true
  ansible.builtin.shell: |
    echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Install Docker
  become: true
  ansible.builtin.apt:
    name: '{{ item }}'
    state: latest
    update_cache: true
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin

- name: Start Docker service and set it to start on boot
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Install docker-compose
  become: true
  ansible.builtin.get_url:
    url: 'https://github.com/docker/compose/releases/download/{{ DOCKER_COMPOSE_VERSION }}/docker-compose-linux-{{ BUILD_ARCHITECTURE }}'
    dest: /usr/local/bin/docker-compose
    mode: u+x,g+x,o+x

- name: Create network (ignores errors; check carefully if this task returns an error)
  become: true
  ansible.builtin.shell: |
    docker network create {{ docker.network }}
  ignore_errors: true
