# List all targets
targets:
    just -l

# Run Caddy playbook
caddy:
    @ansible-playbook -i inventories/staging -D caddy.yml --vault-password-file ./scripts/vault-pass --ask-become-pass

# Run Common playbook
common:
    @ansible-playbook -i inventories/staging -D common.yml --vault-password-file ./scripts/vault-pass --ask-become-pass

# Run Docker playbook
podman:
    @ansible-playbook -i inventories/staging -D podman.yml --vault-password-file ./scripts/vault-pass --ask-become-pass
# Run Dish! Bash! Go! playbook
dish-bash-go:
    @ansible-playbook -i inventories/staging -D dish-bash-go.yml --vault-password-file ./scripts/vault-pass --ask-become-pass

# Run Grafana playbook
grafana:
    @ansible-playbook -i inventories/staging -D grafana.yml --vault-password-file ./scripts/vault-pass --ask-become-pass

# Run Hardening playbook
hardening:
    @ansible-playbook -i inventories/staging -D hardening.yml --vault-password-file ./scripts/vault-pass --ask-become-pass

# Run postgresql playbook
postgresql:
    @ansible-playbook -i inventories/staging -D postgresql.yml --vault-password-file ./scripts/vault-pass --ask-become-pass

# Run Pi-Hole playbook
pihole:
    @ansible-playbook -i inventories/staging -D pihole.yml --vault-password-file ./scripts/vault-pass --ask-become-pass

# Run Ruuvi Reader playbook
ruuvi-reader:
    @ansible-playbook -i inventories/staging -D ruuvi-reader.yml --vault-password-file ./scripts/vault-pass --ask-become-pass

# Run Ruuvi HTTP Server playbook
ruuvi-http:
    @ansible-playbook -i inventories/staging -D ruuvi-http-server.yml --vault-password-file ./scripts/vault-pass --ask-become-pass

# Run Ruuvi Infoscreen Image playbook
ruuvi-img:
    @ansible-playbook -i inventories/staging -D ruuvi-img.yml --vault-password-file ./scripts/vault-pass --ask-become-pass

