# List all targets
targets:
    just -l

# Run Caddy playbook
caddy:
    @ansible-playbook -i inventories/production -D caddy.yml --vault-password-file ./scripts/vault-pass --ask-become-pass

# Run Common playbook
common:
    @ansible-playbook -i inventories/production -D common.yml --vault-password-file ./scripts/vault-pass --ask-become-pass

# Run Docker playbook
podman:
    @ansible-playbook -i inventories/production -D podman.yml --vault-password-file ./scripts/vault-pass --ask-become-pass

# Run Dish! Bash! Go! playbook
dish-bash-go:
    @ansible-playbook -i inventories/production -D dish-bash-go.yml --vault-password-file ./scripts/vault-pass --ask-become-pass

# Run Grafana playbook
beszel:
    @ansible-playbook -i inventories/production -D beszel.yml --vault-password-file ./scripts/vault-pass --ask-become-pass

# Run Hardening playbook
hardening:
    @ansible-playbook -i inventories/production -D hardening.yml --vault-password-file ./scripts/vault-pass --ask-become-pass

# Run High CPU usage notifier playbook
high-cpu-usage-notifier:
    @ansible-playbook -i inventories/production -D high_cpu_usage_notifier.yml --vault-password-file ./scripts/vault-pass --ask-become-pass

# Run postgresql playbook
postgresql:
    @ansible-playbook -i inventories/production -D postgresql.yml --vault-password-file ./scripts/vault-pass --ask-become-pass

# Run Ruuvi HTTP Server playbook
ruuvi-http:
    @ansible-playbook -i inventories/production -D ruuvi-http-server.yml --vault-password-file ./scripts/vault-pass --ask-become-pass

